version: '3.1'
services:
  db:
    image: postgres
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: Stocks
    volumes:
      - postgre-db:/var/lib/postgresql/data/
  stock-py:
    image: prasiddh18/stock-py:stock-py
    container_name: stock-py
        
  ofelia:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.ini:/etc/ofelia/config.ini
volumes:
  postgre-db:
    driver: local



    